<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>30.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRBolao.Model\HRBolao.Model.csproj" />
    <ProjectReference Include="..\HRBolao.Servico\HRBolao.Servico.csproj" />
    <ProjectReference Include="..\HRBolao.ViewModel\HRBolao.ViewModel.csproj" />
  </ItemGroup>

</Project>
